<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Index;

class IndexTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $indices = [
            ["name"=>"AIZAWL","code"=>"1","category"=>"Local"],
            ["name"=>"CHAMPHAI","code"=>"4","category"=>"Local"],
            ["name"=>"LAWNGTLAI","code"=>"7","category"=>"Local"],
            ["name"=>"LUNGLEI","code"=>"2","category"=>"Local"],
            ["name"=>"KOLASIB","code"=>"5","category"=>"Local"],
            ["name"=>"MAMIT","code"=>"8","category"=>"Local"],
            ["name"=>"SIAHA","code"=>"3","category"=>"Local"],
            ["name"=>"SERCHHIP","code"=>"6","category"=>"Local"],
            ["name"=>"KHAWZAWL","code"=>"9","category"=>"Local"],
            ["name"=>"SAITUAL","code"=>"10","category"=>"Local"],
            ["name"=>"HNAHTHIAL","code"=>"11","category"=>"Local"],
            ["name"=>"ANDAMAN & NICOBAR","code"=>"AN","category"=>"Domestic"],
            ["name"=>"ASSAM","code"=>"AS","category"=>"Domestic"],
            ["name"=>"CHHATISGARH","code"=>"CT","category"=>"Domestic"],
            ["name"=>"DELHI","code"=>"DL","category"=>"Domestic"],
            ["name"=>"HARYANA","code"=>"HR","category"=>"Domestic"],
            ["name"=>"JHARKHAND","code"=>"JH","category"=>"Domestic"],
            ["name"=>"LAKHSWADEEP IL.","code"=>"LD","category"=>"Domestic"],
            ["name"=>"MANIPUR","code"=>"MN","category"=>"Domestic"],
            ["name"=>"NAGALAND","code"=>"NL","category"=>"Domestic"],
            ["name"=>"PUNJAB","code"=>"PJ","category"=>"Domestic"],
            ["name"=>"TAMIL NADU","code"=>"TN","category"=>"Domestic"],
            ["name"=>"UTTAR PRADESH","code"=>"UP","category"=>"Domestic"],
            ["name"=>"ANDHRA PRADESH","code"=>"AP","category"=>"Domestic"],
            ["name"=>"BIHAR","code"=>"BH","category"=>"Domestic"],
            ["name"=>"DADRA & NAGAR HY","code"=>"ON","category"=>"Domestic"],
            ["name"=>"GOA","code"=>"GA","category"=>"Domestic"],
            ["name"=>"HIMACHAL  PRADESH","code"=>"HP","category"=>"Domestic"],
            ["name"=>"KARNATAKA","code"=>"KA","category"=>"Domestic"],
            ["name"=>"MADHYA PRADESH","code"=>"MP","category"=>"Domestic"],
            ["name"=>"MEGHALAYA","code"=>"ME","category"=>"Domestic"],
            ["name"=>"ODISHA","code"=>"OD","category"=>"Domestic"],
            ["name"=>"RAJASTHAN","code"=>"RJ","category"=>"Domestic"],
            ["name"=>"TELANGANA","code"=>"TS","category"=>"Domestic"],
            ["name"=>"UTTARAKHAND","code"=>"UT","category"=>"Domestic"],
            ["name"=>"ARUANCHAL  PRADESH","code"=>"AR","category"=>"Domestic"],
            ["name"=>"CHANDIGARH","code"=>"CH","category"=>"Domestic"],
            ["name"=>"DAMAN & DIU","code"=>"DD","category"=>"Domestic"],
            ["name"=>"GUJARAT","code"=>"GJ","category"=>"Domestic"],
            ["name"=>"JAMMU & KASHMIR","code"=>"JK","category"=>"Domestic"],
            ["name"=>"KERELA","code"=>"KL","category"=>"Domestic"],
            ["name"=>"MAHARASHTRA","code"=>"MH","category"=>"Domestic"],
            ["name"=>"MIZORAM","code"=>"MZ","category"=>"Domestic"],
            ["name"=>"PUDUCHERRY","code"=>"PY","category"=>"Domestic"],
            ["name"=>"SIKKIM","code"=>"SK","category"=>"Domestic"],
            ["name"=>"TRIPURA","code"=>"TR","category"=>"Domestic"],
            ["name"=>"WEST BENGAL","code"=>"WB","category"=>"Domestic"],
            ["name"=>"NORTH AMERICA","code"=>"NAM","category"=>"Others"],
            ["name"=>"CARIBBEAN","code"=>"CRB","category"=>"Others"],
            ["name"=>"EASTERN EUROPE","code"=>"EEU","category"=>"Others"],
            ["name"=>"CENTRAL AFRICA","code"=>"CAF","category"=>"Others"],
            ["name"=>"EAST ASIA","code"=>"EAS","category"=>"Others"],
            ["name"=>"CENTRAL  AMERICA","code"=>"CAM","category"=>"Others"],
            ["name"=>"WESTERN EUROPE","code"=>"WEU","category"=>"Others"],
            ["name"=>"MIDDLE EAST","code"=>"MEA","category"=>"Others"],
            ["name"=>"SOUTHERN AFRICA","code"=>"SAF","category"=>"Others"],
            ["name"=>"OCEANIA","code"=>"OCE","category"=>"Others"],
            ["name"=>"SOUTH AMERICA","code"=>"SAM","category"=>"Others"],
            ["name"=>"CENTRAL  EUROPE","code"=>"CEU","category"=>"Others"],
            ["name"=>" NORTHERN AFRICA  ","code"=>"NAF","category"=>"Others"],
            ["name"=>"SOUTH EAST ASIA","code"=>"SEA","category"=>"Others"],
            ["name"=>"PACIFIC","code"=>"PAC","category"=>"Others"],
            ["name"=>"U.K","code"=>"311","category"=>"Others"],
            ["name"=>"FRANCE","code"=>"176","category"=>"Others"],
            ["name"=>"ITALY","code"=>"208","category"=>"Others"],
            ["name"=>"CANADA","code"=>"142","category"=>"Others"],
            ["name"=>"U.A.E","code"=>"278","category"=>"Others"],
            ["name"=>"PAKISTAN","code"=>"253","category"=>"Others"],
            ["name"=>"SOUTH KOREA","code"=>"212","category"=>"Others"],
            ["name"=>"VIETNAM","code"=>"127","category"=>"Others"],
            ["name"=>"MEXICO","code"=>"143","category"=>"Others"],
            ["name"=>"SPAIN","code"=>"200","category"=>"Others"],
            ["name"=>"DENMARK","code"=>"213","category"=>"Others"],
            ["name"=>"FINLAND","code"=>"206","category"=>"Others"],
            ["name"=>"BHUTAN","code"=>"119","category"=>"Others"],
            ["name"=>"SOUTH AFRICA","code"=>"271","category"=>"Others"],
            ["name"=>"CAMBODIA","code"=>"128","category"=>"Others"],
            ["name"=>"TURKEY","code"=>"178","category"=>"Others"],
            ["name"=>"KUWAIT","code"=>"277","category"=>"Others"],
            ["name"=>"NEW ZEALAND","code"=>"121","category"=>"Others"],
            ["name"=>"VATICAN","code"=>"222","category"=>"Others"],
            ["name"=>"U.S.A","code"=>"312","category"=>"Others"],
            ["name"=>"GERMANY","code"=>"184","category"=>"Others"],
            ["name"=>"MALAYSIA","code"=>"230","category"=>"Others"],
            ["name"=>"AUSTR ALIA","code"=>"120","category"=>"Others"],
            ["name"=>"SAUDI AR ABIA","code"=>"279","category"=>"Others"],
            ["name"=>"BANGLADESH","code"=>"124","category"=>"Others"],
            ["name"=>"MYANMAR","code"=>"125","category"=>"Others"],
            ["name"=>"INDONESIA","code"=>"129","category"=>"Others"],
            ["name"=>"BRAZIL","code"=>"144","category"=>"Others"],
            ["name"=>"PORTUGAL","code"=>"201","category"=>"Others"],
            ["name"=>"SWEDEN","code"=>"204","category"=>"Others"],
            ["name"=>"AFGHANISTAN","code"=>"254","category"=>"Others"],
            ["name"=>"MONGOLIA","code"=>"209","category"=>"Others"],
            ["name"=>"BELGIUM","code"=>"207","category"=>"Others"],
            ["name"=>"EGYPT","code"=>"266","category"=>"Others"],
            ["name"=>"ISRAEL","code"=>"180","category"=>"Others"],
            ["name"=>"KENYA","code"=>"265","category"=>"Others"],
            ["name"=>"POLAND","code"=>"297","category"=>"Others"],
            ["name"=>"ROMANIA","code"=>"298","category"=>"Others"],
            ["name"=>"SRI LANKA","code"=>"287","category"=>"Others"],
            ["name"=>"JAPAN","code"=>"211","category"=>"Others"],
            ["name"=>"SWITZERLAND","code"=>"296","category"=>"Others"],
            ["name"=>"SINGAPORE","code"=>"282","category"=>"Others"],
            ["name"=>"IRAN","code"=>"203","category"=>"Others"],
            ["name"=>"CHINA","code"=>"210","category"=>"Others"],
            ["name"=>"THAILAND","code"=>"126","category"=>"Others"],
            ["name"=>"RUSSIA","code"=>"301","category"=>"Others"],
            ["name"=>"ARGENTINA","code"=>"145","category"=>"Others"],
            ["name"=>"NETHERLANDS","code"=>"202","category"=>"Others"],
            ["name"=>"NORWA Y","code"=>"205","category"=>"Others"],
            ["name"=>"NEPAL","code"=>"118","category"=>"Others"],
            ["name"=>"PHILIPPINES","code"=>"130","category"=>"Others"],
            ["name"=>"BAHRAIN","code"=>"272","category"=>"Others"],
            ["name"=>"GREECE","code"=>"177","category"=>"Others"],
            ["name"=>"HONG KONG","code"=>"285","category"=>"Others"],
            ["name"=>"NIGERIA","code"=>"267","category"=>"Others"],
            ["name"=>"TAIWAN","code"=>"286","category"=>"Others"],
            ["name"=>"UZBEKISTAN","code"=>"299","category"=>"Others"],
            ];

            foreach($indices as $index){
                Index::create($index);
            }
    }
}
